# Site settings
title: 올챙이에서 개구기라 되기까지 
email: ram127@naver.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: One sentence introducing yourself or what you do

# Social icons
facebook: ""
linkedin: ""
github: ""
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
